### ISSUE TITLE
Popups/tooltips for markers on GeoJSON layers

### ISSUE THREAD

**Issue by petrovnn** [oliverroick/Leaflet.Deflate#26] opened 2017-11-22 19:00 UTC
Tooltips and maybe popups do not work yet
https://jsfiddle.net/oliverroick/e8vhcsph/1/

**Comment by oliverroick** [comment] 2017-11-22 19:05
Thanks, this is a duplicate of #24, closing...

**Closed by oliverroick** 2017-11-22 19:05 UTC
