### ISSUE TITLE
Customized markers when using MarkerCluster

### ISSUE THREAD

**Issue by banmtG** [oliverroick/Leaflet.Deflate#30] opened 2017-12-04 04:05 UTC
Dear developers,

Thank you very much for your hard work to develop Deflate. I am using it for my project and it is working great. However I don't know how to make customized marker when turn the markercluster option to true. Could you please give me some advice?

Thank you

AD.

**Comment by oliverroick** [comment] 2017-12-04 07:43
Hi @banmtG,

what version are you using? 0.3, which is the current stable version, or do you use the source is `master`?

Could you also share some example code, so I can see what you have tried so far? It'll make it easier for me to help you.

**Comment by banmtG** [comment] 2017-12-07 11:50
Sorry oliverroick for late reply,

Actually I am not so sure which version I am using. I attached here maybe you can tell me.
[L.Deflate.zip](https://github.com/oliverroick/Leaflet.Deflate/files/1538491/L.Deflate.zip)

What I meant was I could not use "markercluster" together with "markerOptions" to have customised marker) as showed below:

function options(f) {
            return {
                    icon: L.icon({
                        iconUrl: 'markers/arboretum.png',
                        iconSize: [16, 16]
                    }),
	              }    
 }

var Dfeatures_arboretum = L.deflate({minSize: 15, , markerCluster: true, markerOptions: options});

When I wrote my code like above, markerCluster doens't work.

I hope I could explain it clearly. 

Thank you very much for your time.

**Comment by oliverroick** [comment] 2017-12-12 07:48
Looks like you're using the correct version but I can't reproduce the error. 

I created an example, which looks like this: 

```javascript
var map = L.map("map").setView([51.550406, -0.140765], 16);

function options() {
    return {
        icon: L.icon({
          iconUrl: 'img/marker.png',
          iconSize: [24, 24]
        })
    }
}

var features = L.deflate({minSize: 20, markerCluster: true, markerOptions: options});
features.addTo(map);

L.polygon([
    [51.472401, -0.468978],
    [51.472401, -0.465545],
    [51.474968, -0.465545],
    [51.474968, -0.468978],
])
.addTo(features);

L.polygon([
    [51.551088, -0.144624],
    [51.550818, -0.143648],
    [51.550701, -0.143718],
    [51.550351, -0.142398],
    [51.550861, -0.142060],
    [51.551155, -0.143160],
    [51.551091, -0.143213],
    [51.551408, -0.144410]
])
.bindPopup('UPS')
.addTo(features);

L.polygon([
    [51.550509, -0.140574],
    [51.550221, -0.140622],
    [51.550208, -0.140456],
    [51.550154, -0.140156],
    [51.550316, -0.140113],
])
.bindPopup('Kentish Town Station')
.addTo(features);

L.polygon([
    [51.550216, -0.140620],
    [51.549754, -0.140695],
    [51.549702, -0.140290],
    [51.549781, -0.140282],
    [51.549807, -0.140475],
    [51.549849, -0.140478],
    [51.549824, -0.140255],
    [51.550117, -0.140196],
    [51.550127, -0.140290],
    [51.550056, -0.140319],
    [51.550084, -0.140488],
    [51.550206, -0.140488],
    [51.550216, -0.140620]
])
.bindPopup('Wahaca')
.addTo(features);

var polyline = L.polyline([
    [51.550836, -0.140684],
    [51.550499, -0.140767],
    [51.550021, -0.140834],
    [51.549684, -0.140891]
], {color: 'red'}).addTo(features);

var marker = L.marker([51.550406, -0.140765]).addTo(features);
```

It works as expected. When you clone the repository you can copy the code in one of the examples, I'd recommend `markercluster.html`. You'll see a map of London, there are a bunch of polygons in North London, which get clustered and there's one in the far West at Heathrow Airport, which isn't added to a cluster and which uses the correct custom marker (you have to zoom out to see it).

Could you produce a full working example of your code (maybe on [JSFiddle](https://jsfiddle.net/))? That would help me better understand what happens in your code. Maybe the problem isn't the clustering or the custom markers, but something else.

**Comment by banmtG** [comment] 2017-12-14 03:40
Hi Oliver Roick,

Thanks for helping me. I check and it works now in the markercluster.html example from repository. However it doesnt not work in my project. Maybe it is something else causing the issues that I have to figure it out myself.

Thanks for bearing with me.

All the best,

**Comment by oliverroick** [comment] 2017-12-14 06:52
Like I said, if you can share the full code that causes the problems, I might be able to help you.

**Comment by oliverroick** [comment] 2018-01-21 11:04
I'm closing the issue now, please re-open if you continue to have problems.

**Closed by oliverroick** 2018-01-21 11:04 UTC
Labels: invalid
