### ISSUE TITLE
Layer control doesn't work with Deflate layer?

### ISSUE THREAD

**Issue by CalebPourchot** [oliverroick/Leaflet.Deflate#61] opened 2018-10-19 15:13 UTC
I thought since L.Deflate is just a FeatureGroup it would work just fine with the built-in Layer control in Leaflet. However, it doesn't seem to remove the features (deflated or not) from the map when the layer is unchecked in the control. Am I missing something?

Here's a fiddle:
https://jsfiddle.net/CalebPourchot/2h7q3L8r/10/

**Comment by oliverroick** [comment] 2018-10-22 13:39
Hi @CalebPourchot,

Thanks for your issue report, that looks like a bug in Leaflet.Deflate. I need to do some investigation on the cause. I'll keep you posted.

**Comment by oliverroick** [comment] 2018-10-22 13:41
Hi @CalebPourchot,

Thanks for the report! This looks like a big in Leaflet.Deflate. I need to investigate the cause of this. I'll keep you posted.

**Comment by CalebPourchot** [comment] 2018-10-22 20:51
It looks like it is this code to me:
```
onRemove: function(map) {
        if (this.clusterLayer) {map.removeLayer(this.cluster)};
        this._map.off("zoomend", this._deflate, this);
        this._map.off("moveend", this._deflate, this);
    }
```

There's the typo in the removeLayer call - this.**cluster**

Also, this apparently just eats the request to remove the layer when you aren't using the markerCluster plug-in?

**Comment by znebby** [comment] 2019-01-02 16:22
This doesn't quite seem to be fixed. I updated the original JSFiddle to alpha 5. https://jsfiddle.net/txzgp3m9/

It now works to disable it, but trying to re-enable it does not work?

Also, I have a related issue. I have two different deflate groups. I add just one of them to the map at the beginning. Trying to add rectangles to the one that hasn't been added to the map gives the following error:

Cannot read property 'getZoom' of undefined

**Comment by oliverroick** [comment] 2019-01-14 08:08
@znebby Thank's for bringing this to my attention. I'm working on a fix. I hope to be able to wrap this during the week.

**Comment by oliverroick** [comment] 2019-01-20 16:05
@znebby I released a new version, which fixes both your issues. You can find an updated version of the jsfiddle here: https://jsfiddle.net/m5ahnbj6/

Closing this now; please do let me know if you have more issues.

**Closed by oliverroick** 2019-01-20 16:05 UTC
Labels: bug

**Comment by znebby** [comment] 2019-01-21 11:53
Thanks so much! This is really close. I have one last issue: https://jsfiddle.net/gqxf1u62/1/

The way my groups are setup, is that there is one group for "all", and another group that is only a subset of all.

However, when you run the fiddle above, and switch from all to subset and back to all, the layer that is meant to contain all the polygons will be missing the polygons that are in the subset. I guess it's adding the new layer before removing the old one?

A workaround is to use duplicate polygon objects in the subset, although that seems inefficient, especially as I'm dealing with a dataset of 10,000 polygons.
